name: "Tutorial"
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - uses: cachix/cachix-action@v12
      with:
        name: tutorial
        extraPullNames: devenv
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix profile install github:cachix/devenv/v0.2
      name: Install devenv.sh
    - run: devenv shell echo ok
    - run: devenv ci
